### ISSUE TITLE
issue related to deployment.

### ISSUE THREAD

**Issue by prathameshsi19** [adiwira-satwika/FIT5120#3]
Integration problem with this latest version uploaded in this branch. While deploying the on Azure server, server can not recognized dependencies thus does not deploy fully functional website. 
Things to consider for next version deployment:
1. Visual studio should recognize all sorts of dependencies of the project. For example studio should recognize different images included in solution. 
2. Image directory path should not differ from original path mentioned in code.

Troubleshooting may help to solve this issue. Please follow below link to troubleshoot:
https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-dotnet-visual-studio

**Comment by adiwira-satwika** [comment]
Issue fixed.
